### ISSUE TITLE
v0.6.0.6 - CellComplex.byCells: module 'topologic' has no atribute 'GlobalCluster''

### ISSUE THREAD

**Issue by brunoperdigao** [wassimj/topologicsverchok#12]
Hi Wassim, I am getting this error whenever I try to create a CellComplex by Cells. I tried in different scenarios and it gets the same error. This error doesn't happen in the previous release.

![image](https://user-images.githubusercontent.com/57102715/144711035-4bb0140b-7d78-4d4d-b8d3-c8571cf88c12.png)

**Comment by brunopostle** [comment]
It might be that you are loading the (older) Topologic library installed with Homemaker. Try disabling Homemaker, then restart blender.

**Comment by brunoperdigao** [comment]
Yeah, that was it. Thanks @brunopostle

**Comment by brunopostle** [comment]
It's my fault, I need to sync with the latest Topologic

**Comment by wassimj** [comment]
@brunopostle thanks for your help! Perhaps we should revisit the idea that Homemaker does not include its own copy of Topologic and simply list it as a dependency; or offer a release that does not include it?

If the users deactivate and reactivate Topologic while Homemaker is active then they get in trouble. I have tested deleting the Topologic copy included in Homemaker and it continued to work fine. You just have to activate Topologic before activating Homemaker.

**Comment by brunopostle** [comment]
Offering an additional version without Topologic or opencascade would help, this would be cross-platform too.

The problem with requiring all users to install TopologicSverchok is that then they have to install Sverchok too.

**Comment by wassimj** [comment]
True. I have been thinking of offering the topologic python module on its own and a separate download for TopologicSverchok that does not have it bundled. Once I get pip or similar figured out, I can offer options to install additional packages.
