### ISSUE TITLE
New Topologic.byGeometry node with Object is not working 

### ISSUE THREAD

**Issue by iproBIM** [wassimj/TopologicSverchok#13]
Hi do i have any mistake please see the Pic attached .thanks
![Object](https://user-images.githubusercontent.com/51295980/145693171-fd9d9b86-32bd-4559-9884-dea5edc9535b.PNG)

**Comment by wassimj** [comment]
It does not accept a collection it seems. First try with just one object. If that works then select them and use Get

**Comment by iproBIM** [comment]
it worked with one Object . when i joint Objects together in Blender the node (Topology.byGeometry) cant read the object any more . thank you for helping

**Comment by wassimj** [comment]
It doesn’t work with a collection. Just select all the objects in the scene and press Get in the Get Objects node. They should appear individually.

**Comment by iproBIM** [comment]
I think i have a special case here after merging the objects in blender as one . but in the old ( Topology.By Geometry ) node it was working good. the new node cannot read the Polygon output so it cannot generate cells . normally with old one i got a Cluster then i extract the cells out of it by using SubTopology node . 
in the pic attached :
1: Error when feeding Polygon . 
2: Working without feeding the Polygon but i dont have Cells .
3: Working good if i have just one object 

![Object New 02](https://user-images.githubusercontent.com/51295980/145694188-98fe190a-ea6a-4f97-a4ca-807fb3ec560a.PNG)

my problem that i need to model all the Cubes ( cells ) again without merging ( Joining ) if i want it to work again .

**Comment by wassimj** [comment]
Please send me the blender file to test. Perhaps we can connect tomorrow to debug

**Comment by wassimj** [comment]
This bug has been fixed in v0.6.0.8. Please test and confirm. If ok, please close this issue. Thanks!
<img width="1920" alt="bugFixed" src="https://user-images.githubusercontent.com/6302909/145703996-a5bc929e-f159-4c7e-8983-5cace49f8638.png">

**Comment by wassimj** [comment]
If you wish to preserve the name, you can also use the Object mode.
<img width="1920" alt="bugFixed02" src="https://user-images.githubusercontent.com/6302909/145704122-b285cfa3-58b7-4b1e-968b-fbf30ed7eb01.png">

**Comment by iproBIM** [comment]
Thank you so much it is working now .
