### ISSUE TITLE
Installation failed on Windows

### ISSUE THREAD

**Issue by spirosloup** [wassimj/TopologicSverchok#14]
Hello. I'm trying to install it on Windows on different Blender versions and I get an error:
Traceback (most recent call last):
   File "............. \ 3.0 \ scripts \ modules \ addon_utils.py", line 351, in enable
     mod = __import __ (module_name)
   File ".............. \ 3.0 \ scripts \ addons \ topologicsverchok \ __ init__.py", line 56, in <module>
     import topologic
ImportError: DLL load failed while importing topologic: The specified procedure could not be found.

**Comment by wassimj** [comment]
Hi
I need more information. It does work if you install nothing ahead of it (no cppyy no homemaker). Just download the release ZIP file and install and activate. You do NOT need to build the software with make etc. it is a one click install. So tell me more how and what you installed.

**Comment by spirosloup** [comment]
I just tried once again in fresh Portable Blender 3.0 without any add-ons installed and discovered that the problem is the Freecad dependency. When i set the Path for the  Freecad , the TopologicSverchock menu disappears. I can't have both enable in the same time. Anyway thanks for the support.

**Comment by wassimj** [comment]
I am suspecting that FreeCAD and Topologic might be conflicting because they both use opencascade. This will require further investigation to see if we can avoid this conflict somehow. I know that Topologic can be imported as a python module within FreeCAD with no issues.

**Comment by jc0112** [comment]
I'm using Blender 2.93 and 3.0 on Windows 10 and I'm getting the same error. Topologic installs fine on its own and with the Sverchok add-ons but when FreeCAD package is linked then it stops working. I installed FreeCAD v19 and 18 with Anaconda and linked the .\bin folder but I keep getting the import error when reloading Topologic. Once I remove the FreeCAD link then I can reload Topologic but when I re-assign it then Topologic nodes break. Is it possible that the Windows Topologic installation is causing an error or perhaps I'm installing FreeCAD wrong? I'd consider switching to Ubuntu if that environment is more stable but would like to troubleshoot this current setup before trying that option.

**Comment by wassimj** [comment]
Can you send me the detailed instructions on how you are installing FreeCAD in Blender? I will test and report back. What I am suspecting is that Topologic and FreeCAD are using different versions of opencascade.

**Comment by jc0112** [comment]
The approach I took was using Anaconda with the command: `conda create --name fcenv --channel conda-forge freecad python=3.9.7`. That produced FreeCAD v19 in 'C:\Users\01123\anaconda3\envs\fcenv\Library\bin' where the FreeCAD.exe and .DLL files are. Then I run Blender as administrator to set the filepath, restart it and the check mark appears but consequently Topologic breaks. I tried regular executable installs of FreeCAD but those didn't link up.

**Comment by wassimj** [comment]
Sadly, FreeCAD and Topologic within BlenderBIM have a clash it seems. This cannot be solved easily if you wish to run both inside Blender. We'll keep investigating and looking for ways to solve this, but for the foreseeable future, you can only use one at a time in Blender.

**Comment by wassimj** [comment]
I believe this is solved. Re-open if not
