### ISSUE TITLE
Topology.Triangulate

### ISSUE THREAD

**Issue by spirosloup** [wassimj/TopologicSverchok#15]
From TwistedTower tutorial. Topology.Triangulate not flatten the list and cause a long  error
![Topology Triangulate](https://user-images.githubusercontent.com/63806612/147712765-ac485754-b051-4501-86ee-6d4faa62c274.jpg)

**Comment by wassimj** [comment]
When you triangulate a Face, it will return a Shell made out of the triangular Faces. CellComplex.ByFaces fails because you are giving it Shells not individual Faces.

**Comment by spirosloup** [comment]
you may need to update the file with what I uploaded. Maybe because of the changes in the code, the tree did not work in the same way as in the video. For example the topology.triangulate node cannot be flattened ......
![Left old Nodetree_rigth New Nodetree](https://user-im
[New TwistedTower.blend.zip](https://github.com/wassimj/TopologicSverchok/files/7793789/New.TwistedTower.blend.zip)
ages.githubusercontent.com/63806612/147770443-96d876d8-c0b4-40b4-a730-766192b94196.jpg)
.

**Comment by wassimj** [comment]
Glad it now works for you
