### ISSUE TITLE
Json dependency install (Linux)

### ISSUE THREAD

**Issue by Sinasta** [wassimj/TopologicSverchok#16]
I get this message in Blender Log:
Topologic - Warning: Could not import ladybug/honeybee/json so some related nodes are not available.
Topologic - Warning: Could not import ladybug/honeybee/json so some related nodes are not available.
Topologic - Warning: Could not import ladybug/honeybee/json so some related nodes are not available.
Which package do i need to install?
pip install json gives:
ERROR: Could not find a version that satisfies the requirement json
ERROR: No matching distribution found for json

**Comment by wassimj** [comment]
You need to install the ladybug and honeybee python modules. Please consult their website on how to do so for your platform. You can inspect the code for HBModel nodes to see what exactly is being imported.

**Comment by Sinasta** [comment]
Thank you for your answer. I did install openstudio, honeybee, honeybee-energy, ladybug through pip. Basically i did install all the dependencies that where written on the readme through pip. Except json because there is no such package on pip.
'Could not import ladybug/honeybee/json' is the only log error i get. So the other libraries are loading fine. My question is what do you mean by installing 'json' ?

**Comment by wassimj** [comment]
json is built-in natively in python. Try in your python console: import json
If that doesn’t work, then there is something wrong with your python installation.

**Comment by wassimj** [comment]
Also I don’t know why ladybug/honeybee has its own json library. It seems to be missing, but this is a question for the ladybug team

**Comment by Sinasta** [comment]
I just tried:
import honeybee
import honeybee_energy
import ladybug
import json
in blender and the error is:

Traceback (most recent call last):
  File "/Text", line 2, in <module>
  File "/home/sinasta/.config/blender/3.2/scripts/modules/honeybee_energy/__init__.py", line 4, in <module>
    from honeybee.logutil import get_logger
ModuleNotFoundError: No module named 'honeybee.logutil'

So the error is clearly on honeybee's side. Sorry for bothering you and thanks for your work.

**Comment by wassimj** [comment]
No problem. I do have it working fine on my windows machine. So hopefully it can be remedied on yours. Best wishes.
