### ISSUE TITLE
It is recommended that the required python modules be integrated into the project

### ISSUE THREAD

**Issue by vkter** [wassimj/TopologicSverchok#19]
It is very difficult for users to install various dependent libraries

**Comment by wassimj** [comment]
The additional python libraries add functionality, but Topologic runs fine without them. Sadly, I cannot improve on how other python libraries are installed.

**Comment by vkter** [comment]
Maybe you can ask a sverchok developer for help.
Add similar panels to the faceplate
![image](https://user-images.githubusercontent.com/74725748/154409431-0d6b89b4-2d79-4987-a628-03cf799eed98.png)

**Comment by wassimj** [comment]
Don’t know any developers that have time, but will add a help wanted tag here. Open source software needs many people to help. Given limited resources, my priority is on core functionality not sverchok at the moment. If you can, please publicise on social media the need to help this project and tag @topologicBIM (on Twitter). Thanks

**Comment by vkter** [comment]
ok，
