### ISSUE TITLE
Can the speed of the node be improved later?

### ISSUE THREAD

**Issue by vkter** [wassimj/TopologicSverchok#20]
It takes a lot of time to generate just a few hundred points.
![image](https://user-images.githubusercontent.com/74725748/154414924-469a55bf-318a-40d2-8d7c-4af7e29c281b.png)

**Comment by wassimj** [comment]
It took 0.025 seconds to generate the circle and 0.173 seconds to convert it to blender geometry. There is an added cost to have the topology information. Topologic on Blender is 8X faster than Topologic on other platforms.

**Comment by vkter** [comment]
It still seems too slow. Is it because of topologic itself?

**Comment by wassimj** [comment]
Slow compared to what? You get more information with Topologic than other methods so you cannot compare geometry creation to other methods.

**Comment by wassimj** [comment]
GitHub issues is meant for bug reports. Please consider using our Discord channel for opinions and general discussion. Thanks.

**Comment by wassimj** [comment]
Discord Channel: https://discord.gg/yUPjYR3t
