### ISSUE TITLE
Feature request: 'intelligent' floorplan generation

### ISSUE THREAD

**Issue by Sinasta** [wassimj/TopologicSverchok#21]
Hello,
I would like to know if somebody has experimented with combining the evolver node from sverchok (Evolutionary Solver, similar to galapagos GH) and Topologic to generate parametric floor-plans (the floorplans could take a relation graph as instructions). Some Examples from Grasshopper:
https://www.youtube.com/watch?v=xIOzF05ZYeU
https://www.youtube.com/watch?v=oUaLOr0cS6M
https://www.youtube.com/watch?v=6tdx_js0Gtc
https://www.youtube.com/watch?v=FC7mJqvcdcE
https://www.youtube.com/watch?v=w6Vs3RZX-1Q
In general i think that Topologic could benefit from the interaction with some 'learning/intelligent' algorithms (evolutionary, ml) even though my opinion is not really fact-based as i don't know enough about the technical parts yet.
I would be really greatful for any answers or discussion.

**Comment by wassimj** [comment]
Thank you for the suggestion. It is something on my mind, but we need resources and more people to contribute code.

**Comment by wassimj** [comment]
For discussion, please post on our Discord channel
