### ISSUE TITLE
NameError("name 'tol' is not defined") in latest release

### ISSUE THREAD

**Issue by Sinasta** [wassimj/TopologicSverchok#23]
I just want to report that In the latest release CellComplex.ByCells is requesting a tolerance input which can't be given within the node as it seems
![Screenshot from 2022-03-07 15-54-29](https://user-images.githubusercontent.com/64699866/157059542-bb214019-5695-4c70-9e80-a0000daa9c8c.png)
.

**Comment by wassimj** [comment]
Thank for spotting this bug! It has been fixed in release v.0.7.0.6
