### ISSUE TITLE
Openstudio Binary Path on Linux

### ISSUE THREAD

**Issue by Sinasta** [wassimj/TopologicSverchok#28]
I would lik to ask if somebody could tell me how to set the Openstudio Binary Path on (Arch)Linux. I have the [Openstudio Python bindings](https://pypi.org/project/openstudio/) installed. Is it enough to set the path to libopenstudiolib.so? Is it really needed to install the entire [Openstudio Suite](https://github.com/NREL/OpenStudio) to execute the simulation?

**Comment by wassimj** [comment]
Not sure about Linux. But on windows, the link to the binary is the link to openstudio.exe not the dll (so it wouldn’t be to the .so file. It is whatever you type on the command line to run openstudio.

**Comment by Sinasta** [comment]
Okay thank you for your answer. So i understand correctly that only 'pip install openstudio' is not enough. The whole 'Openstudio SDK' needs to be installed?

**Comment by wassimj** [comment]
pip install openstudio actually installs the SDK. What is needed is the openstudio application that has the executable.

**Comment by Sinasta** [comment]
Thank you for your answer. For anybody that wants to run openstudio on Linux i found it to work by just downloading the latest [Openstudio](https://github.com/NREL/OpenStudio) Ubuntuh tar.gz release, extracting it and linking topologic to the openstudio bin.
