### ISSUE TITLE
Installation issue on blender in Linux

### ISSUE THREAD

**Issue by Arun-Kanakkassery** [wassimj/TopologicSverchok#29]
Hi, I am trying to install Topologic on Blender in Ubuntu. However, i get this error 
```
File "/home/arun/Apps/blender-2.93.8-linux-x64/2.93/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
ModuleNotFoundError: No module named 'TopologicSverchok-0
```
I have tried this with blender 2.93, 3.0 and 3.1 and sverchok with all the extra nodes installed (have removed FreeCAD library though)

**Comment by wassimj** [comment]
Perhaps you have not installed sverchok? https://github.com/nortikin/sverchok
click on the green code button and download the ZIP file
Do NOT unzip
Start Blender and go to Preferences and Add-ons and Install the downloaded ZIP file

**Comment by wassimj** [comment]
I believe the issue is that TopologicSverchok is compatible with Blender 3.0 or newer. Can you try that?

**Comment by Arun-Kanakkassery** [comment]
Did try TopologicSverchok with Blender 3.0 too

```
Traceback (most recent call last):
  File "/home/arun/Apps/blender-3.0.1-linux-x64/3.0/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
ModuleNotFoundError: No module named 'TopologicSverchok-0'
```
I am using TopologicSverchok-0.8.1.1.zip

**Comment by Sinasta** [comment]
Maybe try renaming the zip to TopologicSverchok before installing

**Comment by wassimj** [comment]
Not sure why it is putting -0 at the end of the name. The latest release for Linux is:
https://github.com/wassimj/TopologicSverchok/releases/tag/v0.7.0.8

**Comment by Arun-Kanakkassery** [comment]
I had to do a fresh Blender installation. This works now. Thank you
