### ISSUE TITLE
When will there be an option for Windows?

### ISSUE THREAD

**Issue by maxim1967** [wassimj/topologicsverchok#3]
When will there be an option for Windows?
They are for Grasshoppers...

**Comment by wassimj** [comment]
It is already available for Windows and MacOS in addition to Linux!

**Comment by maxim1967** [comment]
I didn't understand but what about this message "Topologic custom nodes for sverchok on Blender3D on Linux only (for now)"?

**Comment by maxim1967** [comment]
And how does it install in the Blender for Windows? Please give detailed instructions...

**Comment by wassimj** [comment]
Hi @maxim1967,
To install for Windows, carefully follow the instructions to install TopologicPy in the windows-readme.me. Check the end section for installing Anaconda and a virtual environment for Blender. Then once that is working, install Topologic-Sverchok as usual.
