### ISSUE TITLE
Change U/V Direction of Faces

### ISSUE THREAD

**Issue by Sinasta** [wassimj/TopologicSverchok#30]
Hi, i would like to know if there is any way of changing the U/V direction of individual faces? For example i have multiple different cellcomplexes and i would like to automatically add doors to the internal vertical faces.  For that purpose i use the Face.VertexByParameters node on the internal vertical Faces. But the problem is that when i want to have those Vertex at U = 0.5 and V = 0 the Vertex are not all on the Bottom of their faces. Some are on top, on the side or on the Bottom.
![Screenshot from 2022-04-24 10-58-54](https://user-images.githubusercontent.com/64699866/164968807-b9d43d32-895b-4357-b35d-07145185ce9c.png)
Does somebody know of a way to influence (correct) the U/V direction of those faces? I would like them to be all the same (V pointing upwards).

**Comment by wassimj** [comment]
Unfortunately, faces are not guaranteed to have a particular UV orientation. A workaround (for vertical faces is to check Face.VertexByParameters(0,0), Face.VertexByParameters(1,1), and Face.NormalAtParameters(0.5,0.5) and flip the face using transformations as needed to always get it in the direction that you want.

**Comment by wassimj** [comment]
Another possible hack is to find the lowest and left-most vertex in the wire of the face, then build new face based on:

edges = []
_ = topologic.Vertex.Edges(myWire, edges)
# pick one edge and get its opposite vertex and keep going until you reach the first vertex.
new_wire = topologic.Wire.ByEdges(new_edges)
new_face = topologic.Face.ByExternalBoundary(new_wire)

I have not tested this, so not sure if it will work or not, but worth a try.

**Comment by Sinasta** [comment]
Thank you very much for your answer. I have to admit that i did not completely understand your two propositions (for example how to get the lowest and left-most vertex). I was hoping that there was a simple way Blender, Sverchok or Topologic native but i will try and report back.

**Comment by Sinasta** [comment]
I tried to rebuild the faces with a different order of their wire vertices. But strangely no matter the order of vertices the U/V orientation stays the same. Could you maybe enlighten me of what defines a faces U/V orientation in topologic?

**Comment by wassimj** [comment]
Esentially, Topologic builds a BSpline surface out of the face and calls opencascade's method to get the vertex at the specified U and V.

```
TopologicCore::Vertex::Ptr FaceUtility::VertexAtParameters(const TopologicCore::Face::Ptr& kpFace, const double kU, const double kV)
	{
		Handle(Geom_Surface) pOcctSurface = kpFace->Surface();
		double occtU = 0.0, occtV = 0.0;
		NonNormalizeUV(kpFace, kU, kV, occtU, occtV);

		double occtMinU = 0.0, occtMaxU = 0.0, occtMinV = 0.0, occtMaxV = 0.0;
		ShapeAnalysis::GetFaceUVBounds(kpFace->GetOcctFace(), occtMinU, occtMaxU, occtMinV, occtMaxV);
		ShapeAnalysis_Surface occtSurfaceAnalysis(kpFace->Surface());
		const Handle(Geom_Surface)& rSurface = occtSurfaceAnalysis.Surface();
		Handle(Geom_RectangularTrimmedSurface) pTrimmedSurface = new Geom_RectangularTrimmedSurface(rSurface, occtMinU + 0.0001, occtMaxU - 0.0001, occtMinV + 0.0001, occtMaxV - 0.0001);
		Handle(Geom_BSplineSurface) pBSplineSurface = GeomConvert::SurfaceToBSplineSurface(pTrimmedSurface);

		gp_Pnt occtPoint = pBSplineSurface->Value(occtU, occtV);
		TopologicCore::Vertex::Ptr vertex = TopologicCore::Vertex::ByPoint(new Geom_CartesianPoint(occtPoint));

		return TopologicCore::Vertex::ByPoint(new Geom_CartesianPoint(occtPoint));
	}
```

**Comment by Sinasta** [comment]
Thank you! The simplest way i found for now is to draw an edge between Face.VertexByParameters(0.5,0.5) and Face.VertexByParameters(0,0.5), than check the Z direction of that edge with Edge.Direction. According to the output Z direction != 0 i switch the U and V input. Not the cleanest solution but it works.

I have another question and i don't know if i should open a new issue for that: Is there any way to get all the faces (or aperture faces) that a graph is crossing? (in the screenshot it would be the 4 aperture faces)
![Screenshot from 2022-04-24 18-07-27](https://user-images.githubusercontent.com/64699866/164985756-17cfceb0-4315-442a-8a6b-efe18fe2882f.png)

**Comment by wassimj** [comment]
I will add that as an option. Thanks.
Regarding second question. Place dictionaries in the cells, faces and the apertures (eg key: “type” value: “aperture” or “face” or “cell”). Then the graph vertices will have this dictionary copied into them so you can filter by value at key “type”

**Comment by Sinasta** [comment]
That is awesome! Thank you!
