### ISSUE TITLE
Dictionarybycustomproperties

### ISSUE THREAD

**Issue by Arun-Kanakkassery** [wassimj/TopologicSverchok#31]
i dont see dictionarybycustomproperties in the node menu. This is present in the topologic addon folder. Is this a bug or am i doing something wrong
This option is also not available in the python console from blender

I am using ubuntu linux

![Screenshot from 2022-05-04 14-56-07](https://user-images.githubusercontent.com/58535690/166666148-cf1d6930-bfd1-4f74-973d-3b8c6a563b1d.png)
![Screenshot from 2022-05-04 16-03-25](https://user-images.githubusercontent.com/58535690/166666152-0e0926dd-0f72-47be-ab11-d1abe26c64e0.png)

**Comment by wassimj** [comment]
Hi Arun,
This is a deprecated file. It needs to be removed. It has been replaced with Dictionary.ByObjectProperties

**Comment by wassimj** [comment]
In general, you do not need to consult the files in the nodes folder. If a node is supported, it will be in the menu. If it is not in the menu, that means it is not supported, experimental, or is deprecated.

**Comment by Arun-Kanakkassery** [comment]
thanks, but how do i get the dictionary keys from object property. was referring to the youtube video from Nov 2021.
Do I enter these keys as a seperate list to Dictionary.ByObjectProperties

**Comment by wassimj** [comment]
When you do Topology.ByGeometry the custom properties of the Blender object are transferred to the Topologic Object. So, connect the resulting Topology to Topology.Dictionary and then to Dictionary.Keys and Dictionary.Values to see the keys/values

**Comment by wassimj** [comment]
![TopologicObjectProperties](https://user-images.githubusercontent.com/6302909/166675505-466f8be4-4eae-4aac-b8aa-93e40ba5245a.jpg)

**Comment by Arun-Kanakkassery** [comment]
Got it. thanks
