### ISSUE TITLE
Improve dependency installation

### ISSUE THREAD

**Issue by Tokarzewski** [wassimj/TopologicSverchok#34]
I would like to suggest improving the dependency installation.
This could be done in different ways:
1. single Sverchok node that installs a module or list of modules
2. automatic dependency installation in a form of a script
3...

**Comment by Tokarzewski** [comment]
This could be done in different ways:
1. single Sverchok node that installs a module or list of modules
2. automatic dependency installation in a form of a script
3...

**Comment by Tokarzewski** [comment]
import sys, subprocess

def install_dependency(module):
    call = [sys.executable, '-m', 'pip', 'install', module, '-t', sys.path[0]]
    return subprocess.check_call(call)

install_dependency("scipy")

**Comment by Tokarzewski** [comment]
import sys, subprocess, pkg_resources

def install_dependency(module):
    call = [sys.executable, '-m', 'pip', 'install', module, '-t', sys.path[0]]
    return subprocess.check_call(call)

dependency_list = [#'ifcopenshell',
            'ipfshttpclient',
            "web3",
            "openstudio",
            'honeybee',
            'honeybee-energy',
            'ladybug',
            'py2neo',
            'pyvisgraph',
            'specklepy',
            'numpy',
            'pandas',
            'scipy']

installed_packages = {i.key: i.version for i in pkg_resources.working_set}

for module in dependency_list:
    if module in installed_packages.keys():
        print(f"{module} is already installed.")
    else:
        try:
            install_dependency(module)
            print(f"{module} installed.")
        except:
            print(f"Error during installing {module}")

**Comment by Tokarzewski** [comment]
There is #ifcopenshell because ifcopenshell on pip is currently available only for python 3.9. It is not available for python 3.10.
There is no json on the dependency list because it is already in the python standard library.

**Comment by wassimj** [comment]
Thank you for the suggestion, I have added a node to Topologic to install the optional dependencies. ifcopenshell and homemaker need to be installed separately as they are not pip installable.
![InstallDependencies](https://user-images.githubusercontent.com/6302909/173494611-51c14acc-9e53-4521-b5d6-04f03589fb02.png)
