### ISSUE TITLE
More elaborate README

### ISSUE THREAD

**Issue by luzpaz** [wassimj/TopologicSverchok#41]
- [ ] Screenshots (preferably animated gifs)
- [ ] Usage instructions. 
- [ ] Logos for sverchok and Topologic

**Comment by wassimj** [comment]
We have limited resources. We are happy if other people can contribute. In the meantime, please check the youtube channel for instructional videos: https://www.youtube.com/playlist?list=PLomMn11gzPwTtQMZEWMU0zakg1YRdNuif
There is a logo available for download at: https://topologic.app/press/
