### ISSUE TITLE
energy model bugs and questions

### ISSUE THREAD

**Issue by Sinasta** [wassimj/TopologicSverchok#46]
Hello Wassim i want to do some energy simulations with topologicsverchok on a dataset of apartment cellcomplexes i generated beforehand. While trying this i realised a number of questions and potential bugs. I hope this is the right channel to post them:
1. The example file included in the addon is working well after some slight modifications:

![Screenshot from 2022-09-13 17-39-36](https://user-images.githubusercontent.com/64699866/189945745-d893c1d1-400a-4e19-a239-c0b6d479791f.png)

But when i try to replace the [OSMTemplate-OfficeBuilding-3.2.0.osm](https://github.com/wassimj/TopologicSverchok/blob/main/examples/TopologicEnergy/OSMTemplate-OfficeBuilding-3.2.0.osm) file with the [ASHRAEMidriseApartment.osm](https://github.com/wassimj/TopologicSverchok/blob/main/examples/TopologicEnergy/ASHRAEMidriseApartment.osm) file or the [ASHRAESecondarySchool.osm](https://github.com/wassimj/TopologicSverchok/blob/main/examples/TopologicEnergy/ASHRAESecondarySchool.osm) file an arror appears during the generation of the energymodel by topology:
[ERROR] topologicsverchok.nodes.Topologic.EnergyModelByTopology:70 : tuple index out of range
I suppose that there must be a difference between the working office.osm file and the two others which throw the same error no matter wich space types i assign to the cells.

2. linked to the eroor befor i would like to ask if there is an existing database of osm template files from which i could download the appropriate one for my use case (space types like: Kitchen, living, bathroom etc in a lowrise resedential building)? If there is not such an database could you maybe provide me with an instruction how to create such an template file?

3. my third question is more of an understanding question: in the [EnergyModel.ByTopology node](https://github.com/wassimj/TopologicSverchok/blob/main/nodes/Topologic/EnergyModelByTopology.py) one can specify the room name Key and the room type Key (Name, Type by default). Does the dictionary keys have to stay Name and Type or could i name them ep_name and ep_type for example?

Thanks a lot!

**Comment by Sinasta** [comment]
concerning my 3. question i answered myself by trying: the dictionary keys can be named whatever as long as they are correctly referenced (surprisingly even lower and uppercase doesn't matter)

**Comment by wassimj** [comment]
Hi. I think this needs a zoom meeting to test and debug. I don’t have a database of templates. But I am fairly confident that we can quickly squash that bug

**Comment by wassimj** [comment]
Please email me days and times to meet to wassim.jabi@gmail.com

**Comment by Sinasta** [comment]
Thank you very much for your help!
