### ISSUE TITLE
CellDictionaries are incorrect after rotating Cellcomplex

### ISSUE THREAD

**Issue by Sinasta** [wassimj/TopologicSverchok#47]
Hello Wassim,
It seems like CellDictionary selectors are not rotated with the Cellcomplex when Topology.Rotate is used.
![Screenshot from 2022-10-08 16-34-36](https://user-images.githubusercontent.com/64699866/194712798-b85c07fa-9e87-42ca-8c91-9d0013f39969.png)
if the rotation is below a certain threshold (very low ~1-5 degrees) then the dictionaries stay correct.
![Screenshot from 2022-10-08 16-35-01](https://user-images.githubusercontent.com/64699866/194712839-5fac50b4-c525-4892-8f6d-3a8b4629b343.png)
This is why i assume that the Dictionary selectors are not rotated with the Cellcomplex. I think in general all the selectors should be affected by transformations of the Supertopology. But It could be that i just don't understand the purpose of them not beeing roatated. If so, i would love to know a way to properly rotate them with the supertopology.
Thanks a lot!

**Comment by Sinasta** [comment]
I just checked and the same goes for TopologyScale, TopologyPlace, TopologyTranslate and TopologyTransform

**Comment by wassimj** [comment]
Thanks for reporting this! This seems a bug in the low level C++ code. I can certainly override it in the python code. Can you share the json file of the brep with dictionaries and the blender file? Thank you.

**Comment by Sinasta** [comment]
Sure! thanks for your response.
I am using opencascade 7.5.3 and you are using 7.6. though. Which means my brep strings in the json are: CASCADE Topology V1, (c) Matra-Datavision.
I am afraid that you wont be able to import them into topologicsverchok on your machine.

A python workaround would be nice. For now i have to rotate all the cells one by one and than merge them into a cellcomplex again afterwards, which results in a considerable performance loss. If you would be able to implement a rotation of only the Dictionary selector vertices than that would be great!

[Dictionary_rotation_bug_example.zip](https://github.com/wassimj/TopologicSverchok/files/9739646/Dictionary_rotation_bug_example.zip)

**Comment by wassimj** [comment]
The next release of TopologicSverchok will ensure backward compatibility of the JSON file between OCCT 7.5.3 and 7.6. This has been solved internally. It just needs to be pushed out to github with the next release.
I am debugging this, but as a quick workaround, you can do the following:
![image](https://user-images.githubusercontent.com/6302909/194716995-5f2164af-a06a-41b0-b046-7717d102a30c.png)

**Comment by wassimj** [comment]
I believe I have solved this with the new release 2022-10-08 0.8.2.5. Please test and report back. Thank you.

**Comment by Sinasta** [comment]
It is quite impressive to see how fast you implement new features or fix bugs to be honest! Thank you for the new release. I actually converted my blender node trees to pure python scripts thanks to your [python bindings](https://github.com/wassimj/topologicpy) so i am not using topologicsverchok for my current project. But i just checked if it works with the updated nodes and it does work perfectly fine now. interesting to see the new EnergyModelExportToIDF node aswell.

**Comment by wassimj** [comment]
Great to know! and thanks for the kind words :) I will then close this issue. Please feel free to re-open if there is anything else missed. Thanks.
