### ISSUE TITLE
dgl nodes "not found"

### ISSUE THREAD

**Issue by anydel1** [wassimj/TopologicSverchok#55]
Hi, I'm having a problem with the DGL nodes being "not found". The same with Speckle and Homemaker too.
![dgl_nodes_issue](https://github.com/wassimj/TopologicSverchok/assets/77734628/1c492c23-7a63-4259-9f24-5b1ec0c23951)

**Comment by wassimj** [comment]
This is an experimental version and does not yet include the DGL nodes. We are working on it. If you wish to access DGL, it is now best to use topologicpy within jupyter notebook (use pip install topologicpy --upgrade)

**Comment by wassimj** [comment]
Please check an earlier release of TopologicSverchok for the DGL nodes.

**Comment by anydel1** [comment]
> This is an experimental version and does not yet include the DGL nodes. We are working on it. If you wish to access DGL, it is now best to use topologicpy within jupyter notebook (use pip install topologicpy --upgrade)

Thank you! I'll use Topologicpy. I'm currently working my way through the energy model tutorial and have run into a few problems there too. I think in this case I'm missing something, must be doing something wrong.
