### ISSUE TITLE
Install for Blender 4.1

### ISSUE THREAD

**Issue by lylemills** [wassimj/TopologicSverchok#57]
Hello, 

On trying to install with Blender 4.1 on PC, I am receiving an error once I try to activate the add-on. 

![Topologic_Error](https://github.com/wassimj/TopologicSverchok/assets/62479740/d40190e9-b7e6-40ab-ac66-8a60885aa9b8)

Thank you for any help.

Lyle

**Comment by hd-fatboy** [comment]
getting the same error

**Comment by wassimj** [comment]
The old version of TopologicSverchok is not compatible. We are porting all the nodes to use the new topologicpy. ETA is July. You can access all of topologicpy via custom python nodes that you write yourself
