### ISSUE TITLE
Nodes Reference

### ISSUE THREAD

**Issue by scotus-49** [wassimj/topologicsverchok#7]
Is there any reference information available for the Topologic nodes? On the main Topologic website (topologic.app) the link to user documentation only leads me to the SDK. With almost 60 nodes, I'm trying to find out what they each are supposed to do, and where they interact in the system.

I have read the  conference paper **Topologic: Tools to explore architectural topology** and I found the ideas very interesting. **_Figure 1_** was especially informative. I'm now looking for the information to help me link the theory with the practical side, ie.  Topologic/Sverchok.

I am also trying to convert the published tutorials using Dynamo to the Blender/Sverchok ecosystem so that I can have some idea what the software can do. Any help would be appreciated.

Francis Sim

**Comment by wassimj** [comment]
The following web page has the best source of information. You had the right idea to go through the tutorials one by one and try to map the Dynamo nodes to sverchok. Once you are in Topologic, the nodes should be largely identical and work almost the same way. Input and output will be a bit different.
https://topologic.app/learning/

Beyond that, I am happy to meet with you to give you a tour. Topologic nodes have advanced quite a bit from those on github. I will publish an update soon and I highly recommend that you update Topologicsverchok because I solved quite a bit of bugs.

If you wish to meet with me, please book using http://jabiw.ycb.me

**Comment by scotus-49** [comment]
Thanks - that's the page I've been using to collect information. I'm happy to hear that Topologic/Sverchok is moving forward. I tried duplicating your Youtube Boolean demo using the presently available addon, and it was not quite matching the results in your video, but it worked enough to inspire me to keep going.

Thanks for all your hard work.

**Comment by scotus-49** [comment]
I've just spent most of the day puzzling through your Dynamo/Topologic tutorial info, in particular **Tutorial 02: Creating a Multi-Storey Building**. I even found a [website](https://primer.dynamobim.org/index.html) with sufficiently clear explanations of the insides of the Dynamo program. But in the end,I admit to being totally and utterly confused and not any better informed about the workings of the Topologic program, 

To access basic information about the function of your Topologic nodes, the best (and only) method was to hunt through each separate python code file in the Blender addon for the tooltip information. This does not appear in my Blender node window when using the addon. But these were only scraps of information, not of much practical use.

I cannot find anywhere on the internet any form of a user manual for your Topologic software - only tutorials for Autodesk Dynamo Studio. As I stated above, I could only access the SDK documentation, which tells me nothing useful. As far as I can work out, Topologic is a large complex piece of work, but outside of the world of academia, without information about its basic use and function, it may well not get very far. 

The open source software landscape is littered with abandonware which failed to ignite a spark of interest large enough to reach a critical mass of supporters. I note that the user forum on your website has  zero posts and zero topics. Topologic is not listed in the popular packages section of dynamobim.org.

Good luck with your effort.

**Comment by wassimj** [comment]
Sorry you cannot find clear tutorials. Topologic is not abandonware. But it is not for the faint of heart. It is being used for PhD level research and in large firms. But people keep quiet about it. Check BuroHappold BHoM and Hoare Lea SAM 2.0.
I offered to meet with you and give you a personal tour of it, but up to you. I help people who want to use it. Other than that, we all have free will.

**Comment by scotus-49** [comment]
Thanks for your reply. To make my point clear - I was looking for **information**, not **tutorials**. I have been using computers in my architectural work since the early 1980s, when I landed in charge of a $1m Intergraph system running on a Vax 750. Those were the pioneering days. 

I have been coding now for over 4 decades, as well as building and working from Tokyo to New York. And I know what information I need to find out if a tool is going to be useful or not. Your Topologic might be an extremely useful digital tool, but when there's no relevant information available, I cannot say.

**Comment by wassimj** [comment]
Glad to hear it. I started coding on punch cards. Still I am curious rather than judgmental.

**Comment by scotus-49** [comment]
Sorry If it seemed that I was passing judgement - I too am normally curious, but as a Scotsman I have a large streak of **do it-try it-fix it** in my approach to my work. 

In the late 1970s I was curious enough to go to your home town - Beirut, bang in the middle of the civil war, to have a meeting with some Lebanese architect friends. I had a sea view from my hotel in Hamra Street, and the town was deserted apart from trucks with guns blazing in the middle of the day. I survived though, but lost my kilt during the Israeli bombardments.

Now - I agree completely with your analysis of architectural practice in the digital era - completely! Your work could stir things up into a better direction - I just do not have enough info on your tools, workflow and what they can do to pass any judgement. 

I' reachable at scotus@francissim.de if you want to PM.

Once again, kind regards from lockdown Berlin
